# Generated by Django 6.0.4 on 2026-05-04 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, db_index=True, default='', help_text='Venue address or city for in-person / hybrid events.', max_length=200)),
                ('venue_type', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], db_index=True, default='in_person', max_length=20)),
                ('online_url', models.URLField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Optional map pin (WGS84).', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cover_image', models.URLField(blank=True, default='')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum attendees; null means no limit set.', null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('schedule_items', models.JSONField(blank=True, default=list, help_text='Optional agenda: [{"title","starts_at","ends_at"}] ISO datetimes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx'), models.Index(fields=['category', 'starts_at'], name='events_even_categor_97c86b_idx')],
            },
        ),
    ]
