# Generated by Django 6.0.4 on 2026-05-04 22:19

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    defaults = [
        ("music", "Music"),
        ("tech", "Technology"),
        ("food-drink", "Food & Drink"),
        ("business", "Business"),
        ("arts", "Arts & Culture"),
        ("sports", "Sports & Fitness"),
        ("community", "Community"),
        ("other", "Other"),
    ]
    for slug, name in defaults:
        Category.objects.get_or_create(slug=slug, defaults={"name": name})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
